[package]
name = "gnucash"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.21"
quick-xml = "0.22.0"

[[example]]
name = "open_gnucash"
path = "examples/open_gnucash.rs"